#!/usr/bin/env node
/**
 * Regenerate tests/hermes_cli/fixtures/xterm_unicode11_widths.json
 *
 * Scores every codepoint in the scan ranges against the EXACT xterm.js width
 * table shipped in this repo's node_modules (@xterm/addon-unicode11), pinning
 * the Electron terminal pane's cell model as a committed fixture. A lockfile
 * bump that flips any width then fails tests/hermes_cli/test_width_engine_matrix.py
 * loudly instead of silently re-breaking the "impossible timer" class.
 *
 * Run from the repo root:  node scripts/gen_xterm_width_fixture.js
 */
"use strict";
const addon = require("@xterm/addon-unicode11");
const fs = require("fs");
const path = require("path");

const a = new addon.Unicode11Addon();
let provider = null;
a.activate({
  unicode: {
    register(p) {
      provider = p;
    },
  },
});
if (!provider || typeof provider.wcwidth !== "function") {
  console.error("could not obtain a width provider from @xterm/addon-unicode11");
  process.exit(1);
}

const cps = [];
for (let cp = 0x80; cp < 0x3000; cp++) cps.push(cp);
for (let cp = 0x1f000; cp < 0x1fb00; cp++) cps.push(cp);
cps.push(0xfe0e, 0xfe0f, 0x200d, 0x20e3);

const widths = {};
for (const cp of cps) {
  let w;
  try {
    w = provider.wcwidth(cp);
  } catch (e) {
    w = -99;
  }
  widths[cp.toString(16).toUpperCase()] = w;
}

const pkg = require("@xterm/addon-unicode11/package.json");
const fixture = {
  _note:
    "Generated by scripts/gen_xterm_width_fixture.js — do not hand-edit. " +
    "Widths are the xterm.js Unicode-11 provider's wcwidth() for the Electron " +
    "terminal pane's cell model. Regenerate on lockfile bumps.",
  source: "@xterm/addon-unicode11",
  addon_version: pkg.version,
  provider_version: provider.version || null,
  ranges: ["0x80-0x2FFF", "0x1F000-0x1FAFF", "+ FE0E FE0F 200D 20E3"],
  widths,
};

const out = path.join(__dirname, "..", "tests", "hermes_cli", "fixtures", "xterm_unicode11_widths.json");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, JSON.stringify(fixture, null, 0) + "\n");
console.log(`wrote ${Object.keys(widths).length} entries to ${out}`);
