"""Width-engine matrix: every chrome glyph scores the same across all engines.

prompt_toolkit's diff-repaint never rewrites a cell whose MODEL content is
unchanged; any glyph whose model width differs from the painted width strands
stale cells to its right (the "impossible timer" saga — see FORK.md 2026-10-06
and tests/hermes_cli/test_pt_chrome_no_vs16.py).

This test is layer 2 of the defense:
  1. portable_glyphs allowlist + AST lint (no unvetted codepoint in chrome)
  2. THIS matrix: every codepoint actually used in pt chrome, scored across
     all engines we can measure, must agree — or be a recorded accepted-risk
     (EAW=Ambiguous) so the divergence is a documented decision, not a
     silent pass.
  3. the diff-replay harness (test_diff_replay_no_stale_cells.py) proves the
     mechanism with real pt bytes.

Engines:
  * pt/wcwidth      — prompt_toolkit.utils.get_cwidth (the model pt diffs on)
  * xterm.js U11    — the Electron pane's exact table (committed fixture,
                      regenerated by scripts/gen_xterm_width_fixture.js)
  * kitty-class     — UTR#51 Emoji_Presentation / EAW W,F => 2, else 1;
                      VS16 sequence => 2 (pixel-verified on the user's kitty
                      for ⚡=2, ⚙=1, ⏱=1, 🗜️=2, 🗜=1)
  * ambiguous-wide  — kitty-class with EAW=Ambiguous treated as 2 (iTerm2's
                      "treat ambiguous-width as double-width" pref / CJK
                      locales). Divergence here must be in ACCEPTED_RISK.
"""
from __future__ import annotations

import ast
import json
import pathlib
import unicodedata

import pytest

from hermes_cli.portable_glyphs import ACCEPTED_RISK_SET, PORTABLE_EXTRA_CODEPOINTS

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
_FIXTURE = _REPO_ROOT / "tests" / "hermes_cli" / "fixtures" / "xterm_unicode11_widths.json"

_CHROME_FILES = [
    "hermes_cli/cli_status_bar_mixin.py",
    "hermes_cli/cli_subagent_monitor.py",
    "hermes_cli/cli_process_dock.py",
    "hermes_cli/cli_session_dock.py",
    "hermes_cli/cli_tui_mixin.py",
    "hermes_cli/cli_modal_mixin.py",
    "hermes_cli/cli_tui_runtime_mixin.py",
    "hermes_cli/cli_stream_mixin.py",
]


_PRINTISH = {"print", "cprint", "_cprint", "_console_print", "console_print"}


def _is_printish(call: ast.Call) -> bool:
    f = call.func
    if isinstance(f, ast.Name):
        return f.id in _PRINTISH
    if isinstance(f, ast.Attribute):
        return f.attr in {"print", "cprint"}
    return False


def _chrome_codepoints() -> set[int]:
    """Every non-ASCII codepoint in pt-rendered chrome string constants.

    Exemptions mirror the lint (test_pt_chrome_no_vs16): printish calls are
    scrollback (no pt grid to desync); a lone banned-codepoint literal is a
    sanitizer argument, not content.
    """
    from hermes_cli.portable_glyphs import BANNED_CODEPOINTS

    out: set[int] = set()
    for rel in _CHROME_FILES:
        p = _REPO_ROOT / rel
        if not p.exists():
            continue
        tree = ast.parse(p.read_text(encoding="utf-8"))
        docs = set()
        for node in ast.walk(tree):
            if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                ds = ast.get_docstring(node, clean=False)
                if ds is not None:
                    docs.add(ds)
        scrollback = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and _is_printish(node):
                for sub in ast.walk(node):
                    if isinstance(sub, ast.Constant) and isinstance(sub.value, str):
                        scrollback.add((sub.lineno, sub.col_offset))
        for node in ast.walk(tree):
            if not (isinstance(node, ast.Constant) and isinstance(node.value, str)):
                continue
            if node.value in docs:
                continue
            if (node.lineno, node.col_offset) in scrollback:
                continue
            if len(node.value) == 1 and ord(node.value) in BANNED_CODEPOINTS:
                continue
            for ch in node.value:
                if ord(ch) >= 0x80:
                    out.add(ord(ch))
    return out


def _pt_width(cp: int) -> int:
    from prompt_toolkit.utils import get_cwidth
    return get_cwidth(chr(cp))


def _xterm_width(cp: int) -> int | None:
    data = json.loads(_FIXTURE.read_text())
    return data["widths"].get(f"{cp:X}")


_EP_RANGES = None


def _emoji_presentation(cp: int) -> bool:
    global _EP_RANGES
    if _EP_RANGES is None:
        data = json.loads((_REPO_ROOT / "tests/hermes_cli/fixtures/emoji_presentation_ranges.json").read_text())
        _EP_RANGES = data["ranges"]
    for lo, hi in _EP_RANGES:
        if lo <= cp <= hi:
            return True
        if cp < lo:
            break
    return False


def _kitty_class_width(cp: int, ambiguous_wide: bool = False) -> int:
    ch = chr(cp)
    if _emoji_presentation(cp):
        return 2
    eaw = unicodedata.east_asian_width(ch)
    if eaw in ("W", "F"):
        return 2
    if ambiguous_wide and eaw == "A":
        return 2
    return 1


def test_fixture_is_pinned_to_shipped_xterm_version():
    """The committed fixture must name the addon version it was generated from."""
    data = json.loads(_FIXTURE.read_text())
    assert data["source"] == "@xterm/addon-unicode11"
    assert data.get("addon_version"), "fixture must record the addon version"
    pkg = json.loads((_REPO_ROOT / "node_modules/@xterm/addon-unicode11/package.json").read_text())
    assert data["addon_version"] == pkg["version"], (
        "@xterm/addon-unicode11 version changed — regenerate the fixture: "
        "node scripts/gen_xterm_width_fixture.js"
    )


def test_every_chrome_codepoint_agrees_across_engines():
    """No chrome codepoint may diverge silently between pt and the measured engines.

    A codepoint that pt scores differently from ANY engine is a stranded-cell
    waiting to happen on that engine's terminal. The only allowed divergence is
    EAW=Ambiguous *when the codepoint is explicitly in the accepted-risk set*
    (narrow everywhere by default; may paint wide under an ambiguous-wide pref).
    """
    problems = []
    for cp in sorted(_chrome_codepoints()):
        ch = chr(cp)
        pt = _pt_width(cp)
        xt = _xterm_width(cp)
        kit = _kitty_class_width(cp)
        amb = _kitty_class_width(cp, ambiguous_wide=True)

        divergences = []
        if xt is not None and xt != pt:
            divergences.append(f"xterm.js={xt} pt={pt}")
        if kit != pt:
            divergences.append(f"kitty-class={kit} pt={pt}")
        if amb != pt:
            divergences.append(f"ambiguous-wide={amb} pt={pt}")

        if not divergences:
            continue
        if cp in ACCEPTED_RISK_SET and all("ambiguous-wide" in d for d in divergences):
            continue  # documented acceptance, narrow everywhere by default
        problems.append(f"U+{cp:04X} ({ch!r}): " + "; ".join(divergences))

    assert not problems, (
        "Chrome codepoints diverge between pt's width model and what terminals "
        "paint — each is a stale-cell corruption risk (the 'impossible timer' "
        "class). Replace the glyph with one that measures identically everywhere, "
        "or add it to ACCEPTED_RISK in hermes_cli/portable_glyphs.py with a "
        "documented rationale. Offenders:\n" + "\n".join(problems)
    )


def test_matrix_has_teeth_known_divergent_sequences():
    """Sanity: the matrix's checks would catch the original bug shapes.

    '🗜️' (base+VS16) is the exact shipped corruption: pt says 1 (VS16 is
    zero-width to wcwidth), the kitty-class cluster rule says 2 — the assertion
    the matrix applies to chrome codepoints must flag it when applied to the
    SEQUENCE. ('🗜' bare, the fix, must pass.)
    """
    base = 0x1F5DC

    def kitty_cluster_width(chars: str) -> int:
        ch = chars[0]
        if len(chars) > 1 and chars[1] == "\ufe0f" and ord(ch) >= 0x2190:
            return 2
        return _kitty_class_width(ord(ch))

    # The bug: sequence paints 2, pt scores it 1 -> matrix must call it divergent.
    seq = "\U0001F5DC\ufe0f"
    assert _pt_width(base) == 1
    assert kitty_cluster_width(seq) == 2, "kitty-class cluster rule must say 2 (pixel-verified)"

    # The fix: bare base paints 1 everywhere.
    assert kitty_cluster_width("\U0001F5DC") == 1 == _pt_width(base)

    # And FE0F itself must never appear in chrome constants (banned machinery).
    from hermes_cli.portable_glyphs import BANNED_CODEPOINTS
    assert 0xFE0F in BANNED_CODEPOINTS


def test_allowed_chrome_codepoints_are_allowlisted():
    """Layer-1 invariant: every chrome codepoint is a deliberate allowlist entry."""
    from hermes_cli.portable_glyphs import is_portable_codepoint

    unlisted = [f"U+{cp:04X} ({chr(cp)!r})" for cp in sorted(_chrome_codepoints())
                if not is_portable_codepoint(chr(cp))]
    assert not unlisted, (
        "Chrome uses codepoints not in the portable allowlist "
        "(hermes_cli/portable_glyphs.py PORTABLE_EXTRA_CODEPOINTS). A new "
        "chrome glyph is a deliberate edit there + this matrix passing. "
        f"Unlisted: {unlisted}"
    )
